# Generated by Django 4.2.16 on 2026-04-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("dept", models.CharField(max_length=100)),
                ("date", models.CharField(max_length=50)),
                ("login_time", models.CharField(max_length=50)),
                ("logout_time", models.CharField(default="—", max_length=50)),
                ("hours", models.CharField(default="—", max_length=50)),
                ("extra_hours", models.CharField(default="—", max_length=50)),
                ("tasks", models.TextField(blank=True, default="—")),
                ("status", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
