# Generated by Django 4.2.16 on 2026-04-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_passwordresettoken_attendance_total_break_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="last_status_change",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
