# Generated by Django 4.2.16 on 2026-04-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_attendance_last_status_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordresettoken",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
