# Generated by Django 4.2.16 on 2026-05-07 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_chatmessage_attendance_eight_hour_notified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="api.employeegroup",
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="receiver_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
