# Generated by Django 4.2.16 on 2026-05-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_chatmessage_group_alter_chatmessage_receiver_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="group",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="group_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
