# Generated by Django 4.2.16 on 2026-05-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_chatmessage_group_chatmessage_group_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="screenshot",
            field=models.ImageField(
                blank=True, null=True, upload_to="attendance_screenshots/"
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="chat_images/"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
