# Generated by Django 4.2.16 on 2026-05-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_attendance_screenshot_chatmessage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="last_active",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
