# Generated by Django 4.2.16 on 2026-05-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_attendance_last_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="break_logs",
            field=models.TextField(blank=True, default="[]"),
        ),
    ]
