# Generated by Django 4.2.16 on 2026-05-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_attendance_break_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="aadhar_card",
            field=models.ImageField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="aadhar_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="contact",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="dob",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="pan_card",
            field=models.ImageField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="pan_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
    ]
