# Generated by Django 4.2.16 on 2026-05-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_profile_aadhar_card_profile_aadhar_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="joining_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
