# Generated by Django 4.2.16 on 2026-05-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_profile_joining_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="offline_logs",
            field=models.TextField(blank=True, default="[]"),
        ),
    ]
