# Generated by Django 4.2.16 on 2026-06-22 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_holiday"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceScreenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("screenshot", models.ImageField(upload_to="attendance_screenshots/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodic_screenshots",
                        to="api.attendance",
                    ),
                ),
            ],
        ),
    ]
