# Generated by Django 4.2.16 on 2026-08-01 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_employeesession"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AttendanceScreenshot",
        ),
    ]
