# Generated by Django 4.2.16 on 2026-08-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_delete_attendancescreenshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeesession",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="dept",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="designation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="sheet_employee_id",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="sheet_synced",
            field=models.BooleanField(default=False),
        ),
    ]
