# Generated by Django 4.2.16 on 2026-08-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_employeesession_is_admin_profile_dept_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyJobRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_name", models.CharField(db_index=True, max_length=50)),
                ("run_date", models.DateField(db_index=True)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("detail", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "unique_together": {("job_name", "run_date")},
            },
        ),
    ]
