

services:
  backend:
    build: ./backend
    container_name: brolly-login-backend
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "8001:8001"
    restart: always

  frontend:
    build: ./frontend
    container_name: brolly-login-frontend
    depends_on:
      - backend
    ports:
      - "3001:80"
    restart: always
