

services:
  backend:
    build: ./backend
    # container_name: brolly-login-backend
    container_name: brolly-test-login-backend
    network_mode: host
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3
    ports:
      # - "800:8001"
      - "8003:8003"
    restart: always

  frontend:
    build: ./frontend
    # container_name: brolly-login-frontend
    container_name: brolly-test-login-frontend
    depends_on:
      - backend
    ports:
      - "3003:8003"
    restart: always
